export class ConfigConstants {

  static CONFIGS = {
    'nav.searchKey.placeholder.value': 'Search Images',
    'showImage.image.not.found.message': 'No records found',
    'search.image.pageSize': 10,
    'search.image.pageIndex': [10, 20, 30],
    'image.search.url': 'https://api.unsplash.com/search/photos?query=0&orientation=landscape&per_page=1&page=2',
    'nav.Favorites.dropdown': 'My Favorites',
    'search.image.init,searchKey': 'Nature',

    'addcollectionpopup.close.icon': 'close',
    'addcollectionpopup.add.icon': 'add',
    'addcollectionpopup.remove.icon': 'remove',
    'addcollectionpopup.heading.label': 'Add to collection',
    'addcollectionpopup.buttontext.text': 'Create new collection',
    'addcollectionpopup.imageadd.text': '0 photos',
    'addcollectionpopup.imageremove.text': '1 photos',
    'addcollectionpopup.Collectionname.text': 'Collection Name',
    'addcollectionpopup.Description.text': 'Description (Optional)',
    'addcollectionpopup.button.Createcollection': 'Create Collection',
    'addcollectionpopup.button.Cancel': 'Cancel',
    'addcollectionpopup.create.collection.heading.label': 'Create New Collection',
    'total.phots.label': 'Total Images : ',

    'favourite.label.name': ' Collection',
    'favourite.label.number': '(3)',
    'favourite.collection1.label': 'Collection 1',
    'favourite.collection2.label': 'Collection 2',
    'favourite.collection3.label': 'Collection 3',
    'favourite.author.name': 'Vincent Hawks',
    'favourite.picture.type1': 'Nature',
    'favourite.picture.type2': 'Morning',
    'favourite.picture.type3': 'Animal',
    'favourite.picture.type4': 'Scenery',
    'favourite.picture.type5': 'Forest',
    'favourite.picture.type6': 'Natural Beauty',
    'favourite.collection.description.name': '6 photos.Curated by ',
    'favourite.imgCollection.description': 'Description',
    'favourite.imgCollection.description1': 'Description of Collection 1',
    'favourite.imgCollection.description2': 'Description of Collection 2',
    'favourite.imgCollection.description3': 'Description of collection 3',
    'favourite.button.name.edit': 'Edit',
    'favourite.button.name.share': 'Share',
    'favourite.edit.label': 'Edit Collection',
    'favourite.input.label.name': 'Name',
    'favourite.checkbox.label.name': 'Make Collection Private',
    'favourite.anchor.label.name': 'Delete Collection',
    'favourite.button.label.save': 'Save',
    'favourite.label.photoNum': '5 Photos',
    'favourite.input.length': '60',
    'favourite.textarea.length': '250',
    'addToFavourite.alertMsg': 'Sorry, a collection already exists with this name - ',

    // AUTHORPAGE CONSTANTS
    'author.follwers.label': 'Follwers',
    'author.following.label': 'Following',
    'author.collections.label': 'Collections',
    'author.nav.photos': 'Photos',
    'author.nav.likes': 'Likes',
    'author.nav.collections': 'Collections',
    'author.link.active': 'linkActive',
    'author.link.deactive': 'div_for_photos',

    // EDITCOLLECTION CONSTANTS
    'editcollections.maticon.close': 'close',
    'editcollections.heading.label': 'Edit Collection',
    'editcollections.name.label': 'Name',
    'editcollections.description.label': 'Description',
    'editcollections.delete.button': 'Delete',
    'editcollections.updatename.close': 'Update Name',
    'editcollections.alertMsg': 'Collection Name already exits with the name - ',

    // MANAGEcOLLECTION CONSTANTS
    'manageCollections.head.collectionName': 'Collection Name',
    'manageCollections.para': 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, harum.',
    'manageCollections.image.name': 'Edit Collection',
    'name.already exist.lable': 'Collection Name already exists with the name - ',
    'ok.button.lable': 'Ok'

  };
}
